/*
 * generated by Xtext
 */
package com.incquerylabs.uml.alf;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class ReducedAlfLanguageRuntimeModule extends com.incquerylabs.uml.alf.AbstractReducedAlfLanguageRuntimeModule {

}
