/*
 * generated by Xtext
 */
package com.incquerylabs.uml.alf;

/**
 * Initialization support for running Xtext languages 
 * without equinox extension registry
 */
public class ReducedAlfLanguageStandaloneSetup extends ReducedAlfLanguageStandaloneSetupGenerated{

	public static void doSetup() {
		new ReducedAlfLanguageStandaloneSetup().createInjectorAndDoEMFRegistration();
	}
}

