/******************************************************************************
 *
 * P A C K A G E   D E F I N I T I O N   ( H E A D E R )
 *
 * NAME: Test Package
 *
 * Generated by EMC-C++ 0.7.8
 *
 ******************************************************************************/

#ifndef __TEST_FSM__MAIN_PACKAGE__TEST_COMPONENT__TEST_PACKAGE_DEF_HH
#define __TEST_FSM__MAIN_PACKAGE__TEST_COMPONENT__TEST_PACKAGE_DEF_HH

#ifndef __EMC_CPP_BUILD
#error Generated header file Z:/home/jenkins/wss/BP4110/ws1/Test_FSM/gen/CPP_Linux\Test_FSM\Main_Package\Test_Component\Test_Package_def.hh is not accessible from the handwritten source code.
#else
#if __EMC_CPP_BUILD!=456
#error Header file Z:/home/jenkins/wss/BP4110/ws1/Test_FSM/gen/CPP_Linux\Test_FSM\Main_Package\Test_Component\Test_Package_def.hh was generated by a different version of EMC-C++.
#endif
#endif

#include "Test_FSM/Test_Component/Test_Package_decl.hh"
#include "Test_FSM/Test_Component/Test_Component_def.hh"

#include "Test_FSM/Test_Component/TEST.hh"

#endif
