/*
 * generated by Xtext
 */
package com.incquerylabs.uml.alf.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the IDE.
 */
public class ReducedAlfLanguageUiModule extends com.incquerylabs.uml.alf.ui.AbstractReducedAlfLanguageUiModule {
	public ReducedAlfLanguageUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
