##############################################################################
# P A C K A G E   M A K E   R U L E S
#
# NAME: Main Package
#
# Generated by EMC-C++ 0.7.8
#
##############################################################################

sp 		:= $(sp).x
dirstack_$(sp)	:= $(d)
d	:= $(dir)

dir	:=	$(d)/Test_Component
include	$(dir)/Rules.mk

d	:= $(dirstack_$(sp))
sp	:= $(basename $(sp))
