/*
 * generated by Xtext
 */
package com.incquerylabs.uml.ralf;

import org.eclipse.xtext.resource.IDefaultResourceDescriptionStrategy;

import com.incquerylabs.uml.ralf.scoping.ReducedAlfLanguageResourceDescriptionStrategy;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class ReducedAlfLanguageRuntimeModule extends com.incquerylabs.uml.ralf.AbstractReducedAlfLanguageRuntimeModule {
	
    public Class<? extends IDefaultResourceDescriptionStrategy> bindIDefaultResourceDescriptionStrategy() {
        return ReducedAlfLanguageResourceDescriptionStrategy.class;
    }
}
