/*
 * generated by Xtext
 */
package com.incquerylabs.uml.ralf.ui.contentassist

import com.incquerylabs.uml.ralf.ui.contentassist.AbstractReducedAlfLanguageProposalProvider

/**
 * See https://www.eclipse.org/Xtext/documentation/304_ide_concepts.html#content-assist
 * on how to customize the content assistant.
 */
class ReducedAlfLanguageProposalProvider extends AbstractReducedAlfLanguageProposalProvider {
}
