/******************************************************************************
 *
 * M O D E L   A P I
 *
 * NAME: Test_FSM
 *
 * Generated by EMC-C++ 0.7.8
 *
 ******************************************************************************/

#ifndef __TEST_FSM_API_HH
#define __TEST_FSM_API_HH

namespace Test_FSM {
  int init();
  void run();
  void dispose();
}

#endif
