/******************************************************************************
 *
 * M O D E L   D E F I N I T I O N S
 *
 * NAME: Test_FSM
 *
 * Generated by EMC-C++ 0.7.8
 *
 ******************************************************************************/

#ifndef __TEST_FSM_DEF_HH
#define __TEST_FSM_DEF_HH

#ifndef __EMC_CPP_BUILD
#error Generated header file Z:/home/jenkins/wss/BP4110/ws1/Test_FSM/gen/CPP_Linux\Test_FSM\Test_FSM_def.hh is not accessible from the handwritten source code.
#else
#if __EMC_CPP_BUILD!=456
#error Header file Z:/home/jenkins/wss/BP4110/ws1/Test_FSM/gen/CPP_Linux\Test_FSM\Test_FSM_def.hh was generated by a different version of EMC-C++.
#endif
#endif

#include "Test_FSM/Test_FSM_decl.hh"

#endif
