<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="oopl" nsURI="http://www.ericsson.com/xtumlrt/oopl" nsPrefix="oopl">
  <eClassifiers xsi:type="ecore:EClass" name="OOPLClass" abstract="true">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="Representation of XTUML class ({@link org.eclipse.papyrusrt.xtumlrt.xtuml.XTClass}) for OOP languages."/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="xtClass" lowerBound="1"
        eType="ecore:EClass ../../org.eclipse.papyrusrt.xtumlrt.xtuml.model/model/xtuml.ecore#//XTClass"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="referenceStorage" upperBound="-1"
        eType="#//OOPLClassReferenceStorage"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="OOPLType" abstract="true">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="Representation of common type ({@link org.eclipse.papyrusrt.xtumlrt.common.Type}) for OOP languages."/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="commonType" lowerBound="1"
        eType="ecore:EClass ../../org.eclipse.papyrusrt.xtumlrt.common.model/model/common.ecore#//Type"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="OOPLClassReference" abstract="true"
      eSuperTypes="#//OOPLType">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="Reference type in OOP languages to store reference to the OOP representation of a model class ({@link com.ericsson.xtumlrt.oopl.OOPLClass})."/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="class" lowerBound="1" eType="#//OOPLClass"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="OOPLClassReferenceCollection" abstract="true"
      eSuperTypes="#//OOPLType">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="Collection type in OOP languages to store references to the OOP representation of model classes ({@link com.ericsson.xtumlrt.oopl.OOPLClass})."/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="class" lowerBound="1" eType="#//OOPLClass"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="OOPLClassRefSimpleCollection" abstract="true"
      eSuperTypes="#//OOPLClassReferenceCollection">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="Simple (non-associative) collection type in OOP languages to store references to the OOP representation of model classes ({@link com.ericsson.xtumlrt.oopl.OOPLClass})."/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="kind" ordered="false" unique="false"
        lowerBound="1" eType="#//SimpleCollectionKind" defaultValueLiteral="SIMPLY_LINKED_LIST"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="OOPLClassRefAssocCollection" abstract="true"
      eSuperTypes="#//OOPLClassReferenceCollection">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="Associative collection type in OOP languages to store references to the OOP representation of model classes ({@link com.ericsson.xtumlrt.oopl.OOPLClass}) indexed by one of the attributes ({@link org.eclipse.papyrusrt.xtumlrt.common.Attribute}) of the class."/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="key" lowerBound="1" eType="ecore:EClass ../../org.eclipse.papyrusrt.xtumlrt.common.model/model/common.ecore#//Attribute"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="kind" ordered="false" unique="false"
        lowerBound="1" eType="#//AssociativeCollectionKind" defaultValueLiteral="UNORDERED_SET"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="SimpleCollectionKind">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="Enumeration of the possible simple class reference collection kinds to be used for attribute kind in class {@link com.ericsson.xtumlrt.oopl.OOPLClassRefSimpleCollection}."/>
    </eAnnotations>
    <eLiterals name="INDEXED_ARRAY"/>
    <eLiterals name="SIMPLY_LINKED_LIST" value="1"/>
    <eLiterals name="DOUBLY_LINKED_LIST" value="2"/>
    <eLiterals name="DOUBLE_ENDED_QUEUE" value="3"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="AssociativeCollectionKind">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="Enumeration of the possible associative class reference collection kinds to be used for attribute kind in class {@link com.ericsson.xtumlrt.oopl.OOPLClassRefAssocCollection}."/>
    </eAnnotations>
    <eLiterals name="UNORDERED_SET"/>
    <eLiterals name="ORDERED_SET" value="1"/>
    <eLiterals name="UNORDERED_MULTISET" value="2"/>
    <eLiterals name="ORDERED_MULTISET" value="3"/>
    <eLiterals name="UNORDERED_MAP" value="4"/>
    <eLiterals name="ORDERED_MAP" value="5"/>
    <eLiterals name="UNORDERED_MULTIMAP" value="6"/>
    <eLiterals name="ORDERED_MULTIMAP" value="7"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="OOPLClassReferenceStorage" abstract="true">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="Storage for references of a class ({@link com.ericsson.xtumlrt.oopl.OOPLClass}) for queries that are made directly on the class or for a relation ({@link com.ericsson.xtumlrt.oopl.OOPLRelation}) if queries are made across the relation. Storage may be a single reference (for signleton classes and x-to-one relations) or a collection of references (for all other classes and x-to-many relations). Multiple storages for the same class or relation are possible if different queries require different access to the references (e.g. maps with different keys)."/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="type" lowerBound="1" eType="#//OOPLType"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="OOPLRelation" abstract="true">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="Representation of XTUML relation ({@link org.eclipse.papyrusrt.xtumlrt.xtuml.XTRelation}) for OOP languages."/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="xtRelation" lowerBound="1"
        eType="ecore:EClass ../../org.eclipse.papyrusrt.xtumlrt.xtuml.model/model/xtuml.ecore#//XTRelation"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="referenceStorage" upperBound="-1"
        eType="#//OOPLClassReferenceStorage"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="OOPLNameProvider" abstract="true">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="Abstract provider class for names in the target language domain."/>
    </eAnnotations>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="OOPLDerivedNameProvider" eSuperTypes="#//OOPLNameProvider">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="Provider class for names of elements in the target language domain that do not exist in the model domain but are derived during population of the target-language dependent part of the translation metamodel."/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" ordered="false" unique="false"
        lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="OOPLExistingNameProvider" eSuperTypes="#//OOPLNameProvider">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="Provider class for names of elements in the target language domain that also exist in the model domain (descendats of {@link org.eclipse.papyrusrt.xtumlrt.common.NamedElement})."/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="commonNamedElement" eType="ecore:EClass ../../org.eclipse.papyrusrt.xtumlrt.common.model/model/common.ecore#//NamedElement"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="OOPLBasicType" abstract="true" eSuperTypes="#//OOPLType">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="Basic type in OOP languages correstponding to common type {@link org.eclipse.papyrusrt.xtumlrt.common.PrimitiveType}."/>
    </eAnnotations>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="OOPLEnumType" abstract="true" eSuperTypes="#//OOPLType">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="Enumeration type in OOP languages corresponding to common type {@link org.eclipse.papyrusrt.xtumlrt.common.Enumeration}. Consists of structure members ({@link com.ericsson.xtumlrt.oopl.OOPLEnumerator})."/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="enumerators" lowerBound="1"
        upperBound="-1" eType="#//OOPLEnumerator" changeable="false" derived="true">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="{&#xD;&#xA;&#x9;OOPLType.commonType(ooplType, type);&#xD;&#xA;&#x9;Enumeration(type);&#xD;&#xA;&#x9;Enumeration.literals(type, enumerator);&#xD;&#xA;&#x9;OOPLEnumerator.commonEnumerationLiteral(ooplEnumerator, enumerator);&#xD;&#xA;}&#xD;&#xA;"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="defaultValue" lowerBound="1"
        eType="#//OOPLEnumerator" changeable="false" derived="true">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="{&#xD;&#xA;&#x9;OOPLType.commonType(ooplType, type);&#xD;&#xA;&#x9;Enumeration(type);&#xD;&#xA;&#x9;Enumeration.defaultValue(type, enumerator);&#xD;&#xA;&#x9;OOPLEnumerator.commonEnumerationLiteral(ooplEnumerator, enumerator);&#xD;&#xA;}&#xD;&#xA;"/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="OOPLEnumerator" abstract="true">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="Member of structure type ({@link com.ericsson.xtumlrt.oopl.OOPLEnumType}) in OOP languages corresponding to ({@link org.eclipse.papyrusrt.xtumlrt.common.EnumerationLiteral})."/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="commonEnumerationLiteral"
        lowerBound="1" eType="ecore:EClass ../../org.eclipse.papyrusrt.xtumlrt.common.model/model/common.ecore#//EnumerationLiteral"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="OOPLStructType" abstract="true" eSuperTypes="#//OOPLType">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="Structure type in OOP languages corresponding to common type {@link org.eclipse.papyrusrt.xtumlrt.common.StructType}. Consists of structure members ({@link com.ericsson.xtumlrt.oopl.OOPLStructMember})."/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="members" lowerBound="1"
        upperBound="-1" eType="#//OOPLStructMember" changeable="false" derived="true">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="{&#xD;&#xA;&#x9;OOPLType.commonType(ooplType, type);&#xD;&#xA;&#x9;StructType(type);&#xD;&#xA;&#x9;StructType.structMembers(type, member);&#xD;&#xA;&#x9;OOPLStructMember.commonMember(ooplStructMember, member);&#xD;&#xA;}&#xD;&#xA;"/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="OOPLStructMember" abstract="true">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="Member of structure type ({@link com.ericsson.xtumlrt.oopl.OOPLStructType}) in OOP languages corresponding to ({@link org.eclipse.papyrusrt.xtumlrt.common.StructMember})."/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="commonMember" lowerBound="1"
        eType="ecore:EClass ../../org.eclipse.papyrusrt.xtumlrt.common.model/model/common.ecore#//StructMember"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="type" lowerBound="1" eType="#//OOPLType"
        changeable="false" derived="true">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="{&#xD;&#xA;&#x9;OOPLStructMember.commonMember.type(ooplStructMember, type);&#xD;&#xA;&#x9;OOPLType.commonType(ooplType, type);&#xD;&#xA;}"/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="OOPLSequence" abstract="true" eSuperTypes="#//OOPLType">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="Sequence (array, set or multiset) type in OOP languages. Eelements are OOP types ({@link com.ericsson.xtumlrt.oopl.OOPLType})."/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="elementType" lowerBound="1"
        eType="#//OOPLType"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="orderedness" ordered="false"
        unique="false" lowerBound="1" eType="#//SequenceOrderednessKind"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="uniqueness" ordered="false"
        unique="false" lowerBound="1" eType="#//SequenceUniquenessKind"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="SequenceOrderednessKind">
    <eLiterals name="UNORDERED"/>
    <eLiterals name="ORDERED" value="1"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="SequenceUniquenessKind">
    <eLiterals name="NON_UNIQUE"/>
    <eLiterals name="UNIQUE" value="1"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="OOPLUserDefinedType" abstract="true"
      eSuperTypes="#//OOPLType">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="User defined type in OOP languages correstponding to common type {@link org.eclipse.papyrusrt.xtumlrt.common.UserDefinedType}. Based on any OOP type ({@link com.ericsson.xtumlrt.oopl.OOPLType})."/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="baseType" lowerBound="1"
        eType="#//OOPLType"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="NewEClass19"/>
</ecore:EPackage>
