package com.incquerylabs.emdw.cpp.performance.test.config;

public enum ModificationType {
    SMALL_STRUCTURE__ATTRIBUTE__ADD,
    SMALL_STRUCTURE__ATTRIBUTE__REMOVE,
    SMALL_STRUCTURE__TRANSITION__ADD,
    SMALL_STRUCTURE__TRANSITION__REMOVE,
    SMALL_BEHAVIOR__ACTION_CODE,
    HIGH_LEVEL__COMPONENT__ADD,
    HIGH_LEVEL__COMPONENT__REMOVE,
    HIGH_LEVEL__PACKAGE__ADD,
    HIGH_LEVEL__PACKAGE__MOVE,
    HIGH_LEVEL__PACKAGE__REMOVE,
    HIGH_LEVEL__PACKAGE__RENAME,
    NONE
}
