/*
 * generated by Xtext
 */
package com.incquerylabs.uml.ralf;

import org.eclipse.xtext.junit4.IInjectorProvider;

import com.google.inject.Injector;

public class ReducedAlfLanguageUiInjectorProvider implements IInjectorProvider {
	
	@Override
	public Injector getInjector() {
		return com.incquerylabs.uml.ralf.ui.internal.ReducedAlfLanguageActivator.getInstance().getInjector("com.incquerylabs.uml.ralf.ReducedAlfLanguage");
	}
	
}
