/*******************************************************************************
 * Copyright (c) 2015-2016 IncQuery Labs Ltd. and Ericsson AB
 * All rights reserved. This program and the accompanying materials
 * are made available under the terms of the Eclipse Public License v1.0
 * which accompanies this distribution, and is available at
 * http://www.eclipse.org/legal/epl-v10.html
 *
 * Contributors:
 *     Akos Horvath, Abel Hegedus, Zoltan Ujhelyi, Daniel Segesdi, Tamas Borbas, Robert Doczi, Peter Lunk, Istvan Papp - initial API and implementation
 *******************************************************************************/
/******************************************************************************
 * 
 * M A I N
 * 
 * NAME: main
 * 
 * Generated by EMDW-MC
 * 
 ******************************************************************************/


#include "ExternalClasses/ExternalClassesComp/ExternalClassesComp_def.hh"

int main(int , char **) {
    ::ExternalClasses::ExternalClassesComp::InternalClasses::Gambler gambler;
    gambler.gamble();
    gambler.hackRandomGenerator(24);
    gambler.gamble();
    gambler.gamble();
    gambler.hackRandomGenerator(24);
    gambler.gamble();
}
