/******************************************************************************
 * 
 * M A I N
 * 
 * NAME: main
 * 
 * Generated by EMDW-MC
 * 
 ******************************************************************************/


#include "ExternalClasses/ExternalClassesComp/ExternalClassesComp_def.hh"

int main(int , char **) {
    ::ExternalClasses::ExternalClassesComp::InternalClasses::Gambler gambler;
    gambler.gamble();
    gambler.hackRandomGenerator(24);
    gambler.gamble();
    gambler.gamble();
    gambler.hackRandomGenerator(24);
    gambler.gamble();
}
