##############################################################################
# M O D E L   M A K E   R U L E S
#
# NAME: Test_FSM
#
# Generated by EMC-C++ 0.7.8
#
##############################################################################

sp 		:= $(sp).x
dirstack_$(sp)	:= $(d)
d	:= $(dir)

dir	:=	$(d)/Test_Component
include	$(dir)/Rules.mk
dir := $(d)/Runtime
include	$(dir)/Rules.mk

SOURCES_$(d)	:= $(wildcard $(d)/*.cc)
OBJECTS_$(d)	:= $(SOURCES_$(d):%.cc=%.o)

SOURCES	:= $(SOURCES) $(SOURCES_$(d))
OBJECTS	:= $(OBJECTS) $(OBJECTS_$(d))

d	:= $(dirstack_$(sp))
sp	:= $(basename $(sp))
