/******************************************************************************
 *
 * U N I Q U E N U M B E R   B O D Y
 *
 * NAME: unique_number.cc
 *
 * Generated by EMDW-MC
 *
 ******************************************************************************/

#include "unique_number.hh"

unsigned long ::unique_number::max_id;
