##############################################################################
# C O M P O N E N T   M A K E   R U L E S
#
# NAME: Test Component
#
# DESCRIPTION
#
# The purpose of the Optical Disk Cabinet Management System is to make optical
# disks available for reading and writing. To do this the system must track
# where a disk currently resides (either inside or outside the cabinet), as
# well as causes the disk to be moved to a drive. The system is also
# responsible for putting disks back in a known location after use.
# 
# The system is not responsible for actually reading and writing the disks.
# 
# Prominent Objects: Disk, Slot, Robot, EE Port
# 
# Copyright 1994 by Project Technology, Inc.
# All rights reserved
#
#
# Generated by EMC-C++ 0.7.8
#
##############################################################################

sp 		:= $(sp).x
dirstack_$(sp)	:= $(d)
d	:= $(dir)

SOURCES_$(d)	:= $(wildcard $(d)/*.cc)
OBJECTS_$(d)	:= $(SOURCES_$(d):%.cc=%.o)

SOURCES	:= $(SOURCES) $(SOURCES_$(d))
OBJECTS	:= $(OBJECTS) $(OBJECTS_$(d))

d	:= $(dirstack_$(sp))
sp	:= $(basename $(sp))
