/******************************************************************************
 *
 * C O M P O N E N T   M A I N   ( H E A D E R )
 *
 * NAME: Test Component
 *
 * DESCRIPTION
 *
 * The purpose of the Optical Disk Cabinet Management System is to make optical
 * disks available for reading and writing. To do this the system must track
 * where a disk currently resides (either inside or outside the cabinet), as
 * well as causes the disk to be moved to a drive. The system is also
 * responsible for putting disks back in a known location after use.
 * 
 * The system is not responsible for actually reading and writing the disks.
 * 
 * Prominent Objects: Disk, Slot, Robot, EE Port
 * 
 * Copyright 1994 by Project Technology, Inc.
 * All rights reserved
 *
 *
 * Generated by EMC-C++ 0.7.8
 *
 ******************************************************************************/

#ifndef __TEST_FSM__MAIN_PACKAGE__TEST_COMPONENT_MAIN_HH
#define __TEST_FSM__MAIN_PACKAGE__TEST_COMPONENT_MAIN_HH

#ifndef __EMC_CPP_BUILD
#error Generated header file Z:/home/jenkins/wss/BP4110/ws1/Test_FSM/gen/CPP_Linux\Test_FSM\Main_Package\Test_Component\Test_Component_main.hh is not accessible from the handwritten source code.
#else
#if __EMC_CPP_BUILD!=456
#error Header file Z:/home/jenkins/wss/BP4110/ws1/Test_FSM/gen/CPP_Linux\Test_FSM\Main_Package\Test_Component\Test_Component_main.hh was generated by a different version of EMC-C++.
#endif
#endif

#include "Test_FSM/Main_Package/Test_Component/Test_Component_decl.hh"

namespace Test_FSM {
  namespace Main_Package {
    namespace Test_Component {
      class Test_Component_main {
      public:
        Test_Component_main() {}
      };
    }
  }
}

#endif
