/******************************************************************************
 *
 * C O M P O N E N T   D E C L A R A T I O N S
 *
 * NAME: Test Component
 *
 * DESCRIPTION
 *
 *
 * Dummy Skeleton for State Machine generator testing
 *
 ******************************************************************************/

#ifndef __TEST_FSM__MAIN_PACKAGE__TEST_COMPONENT_DECL_HH
#define __TEST_FSM__MAIN_PACKAGE__TEST_COMPONENT_DECL_HH

#ifndef __EMC_CPP_BUILD
#error Generated header file Z:/home/jenkins/wss/BP4110/ws1/Test_FSM/gen/CPP_Linux\Test_FSM\Main_Package\Test_Component\Test_Component_decl.hh is not accessible from the handwritten source code.
#else
#if __EMC_CPP_BUILD!=456
#error Header file Z:/home/jenkins/wss/BP4110/ws1/Test_FSM/gen/CPP_Linux\Test_FSM\Main_Package\Test_Component\Test_Component_decl.hh was generated by a different version of EMC-C++.
#endif
#endif

#include "Test_FSM/Test_FSM_decl.hh"
#include "Test_FSM/Main_Package/Test_Component/Test_Package_decl.hh"
#include "Test_FSM/Main_Package/Test_Component/Test_Component_main.hh"

#endif
