<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="valuedescriptor" nsURI="http://www.incquerylabs.com/emdw/valuedescriptor"
    nsPrefix="valuedescriptor">
  <eClassifiers xsi:type="ecore:EClass" name="ValueDescriptor" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="baseType" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="templateTypes" upperBound="-1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="fullType" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="stringRepresentation" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="valueRepresentation" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="pointerRepresentation"
        lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="LiteralDescriptor" eSuperTypes="#//ValueDescriptor"/>
  <eClassifiers xsi:type="ecore:EClass" name="VariableDescriptor" abstract="true"
      eSuperTypes="#//ValueDescriptor"/>
  <eClassifiers xsi:type="ecore:EClass" name="OperationCallDescriptor" eSuperTypes="#//ValueDescriptor"/>
  <eClassifiers xsi:type="ecore:EClass" name="SingleVariableDescriptor" eSuperTypes="#//VariableDescriptor"/>
  <eClassifiers xsi:type="ecore:EClass" name="CollectionVariableDescriptor" eSuperTypes="#//VariableDescriptor"/>
  <eClassifiers xsi:type="ecore:EClass" name="PropertyAccessDescriptor" abstract="true"
      eSuperTypes="#//ValueDescriptor"/>
  <eClassifiers xsi:type="ecore:EClass" name="PropertyReadDescriptor" eSuperTypes="#//PropertyAccessDescriptor"/>
  <eClassifiers xsi:type="ecore:EClass" name="PropertyWriteDescriptor" eSuperTypes="#//PropertyAccessDescriptor"/>
  <eClassifiers xsi:type="ecore:EClass" name="ParameterDescriptor" eSuperTypes="#//VariableDescriptor"/>
</ecore:EPackage>
