/******************************************************************************
 * 
 * M A I N
 * 
 * NAME: main
 * 
 * Generated by EMDW-MC
 * 
 ******************************************************************************/


#include "PingPongOuter/Component/Component_def.hh"

int main(int , char **) {
    // TODO: your code
}
